const products = [
  {
    id: 1,
    name: "Cable Management Kit (300 PCS)",
    nameAr: "طقم تنظيم الكابلات (300 قطعة)",
    slug: "cable-management-kit-300pcs",
    description: "Fast adhesive cable organizer - 300 pieces",
    descriptionAr: "منظم كابلات لاصق سريع - 300 قطعة",
    price: 65,
    category: "Workspace",
    featured: true,
    image: "📦",
    images: ["📦"],
    colors: "Black-Multi",
    packaging: "Each set separately (50 packages)",
    detailedDescription: "Professional 300-piece cable management solution with fast adhesive backing. Perfect for organizing cables at your desk, home entertainment center, or office workspace. Includes various sizes of cable clips, ties, and holders to keep all your cables neat and tangle-free.",
    detailedDescriptionAr: "حل احترافي لإدارة الكابلات مكون من 300 قطعة مع ظهر لاصق سريع. مثالي لتنظيم الكابلات على مكتبك أو مركز الترفيه المنزلي أو مساحة العمل. يشمل أحجام مختلفة من مشابك الكابلات والروابط والحوامل للحفاظ على جميع كابلاتك منظمة وخالية من التشابك.",
    specifications: [
      "300 pieces total",
      "Fast adhesive backing",
      "Multiple sizes included",
      "Black and multicolor options",
      "Reusable design"
    ]
  },
  {
    id: 2,
    name: "Colorful Hook Loop Straps (15cm)",
    nameAr: "أشرطة حلقية ملونة (15 سم)",
    slug: "colorful-hook-loop-straps-15cm",
    description: "Reusable adjustable cable straps - 50 pieces",
    descriptionAr: "أشرطة كابلات قابلة لإعادة الاستخدام - 50 قطعة",
    price: 45,
    category: "Workspace",
    featured: false,
    image: "🎨",
    images: ["🎨"],
    colors: "Red, Blue, Green, Black, Yellow",
    packaging: "Each pack contains (10 Red, 10 Blue, 10 Green, 10 Black, 10 Yellow)",
    detailedDescription: "Eco-friendly double-sided strong adhesive reusable adjustable washable hook loop straps. Perfect for organizing cables, securing items, or bundling cords. Each 15cm strap is durable, washable, and can be reused hundreds of times. Color-coded system makes cable identification easy.",
    detailedDescriptionAr: "أشرطة حلقية صديقة للبيئة ذات وجهين لاصقة قوية قابلة لإعادة الاستخدام وقابلة للغسل. مثالية لتنظيم الكابلات أو تأمين الأشياء أو ربط الأسلاك. كل شريط 15 سم متين وقابل للغسل ويمكن إعادة استخدامه مئات المرات. نظام ترميز الألوان يجعل تحديد الكابلات سهلاً.",
    specifications: [
      "Length: 15cm each",
      "50 pieces total (10 of each color)",
      "Eco-friendly materials",
      "Double-sided adhesive",
      "Washable and reusable",
      "Colors: Red, Blue, Green, Black, Yellow"
    ]
  },
  {
    id: 3,
    name: "Black Hook Loop Straps (15cm)",
    nameAr: "أشرطة حلقية سوداء (15 سم)",
    slug: "black-hook-loop-straps-15cm",
    description: "Professional black cable straps - 50 pieces",
    descriptionAr: "أشرطة كابلات سوداء احترافية - 50 قطعة",
    price: 42,
    category: "Workspace",
    featured: false,
    image: "⚫",
    images: ["⚫"],
    colors: "Black",
    packaging: "Each pack contains (50 Black)",
    detailedDescription: "Professional-grade black hook loop straps for a clean, uniform look in any workspace. Double-sided eco-friendly strong adhesive with reusable, adjustable, and washable design. Ideal for professional installations, home theaters, or office cable management where aesthetics matter.",
    detailedDescriptionAr: "أشرطة حلقية سوداء احترافية للحصول على مظهر نظيف وموحد في أي مساحة عمل. لاصق قوي صديق للبيئة ذو وجهين مع تصميم قابل لإعادة الاستخدام وقابل للتعديل والغسل. مثالي للتركيبات الاحترافية أو المسارح المنزلية أو إدارة كابلات المكاتب حيث تهم الجماليات.",
    specifications: [
      "Length: 15cm each",
      "50 pieces (all black)",
      "Eco-friendly materials",
      "Double-sided adhesive",
      "Washable and reusable",
      "Professional appearance"
    ]
  },
  {
    id: 4,
    name: "Colorful Silicon Cable Straps",
    nameAr: "أشرطة سيليكون ملونة للكابلات",
    slug: "colorful-silicon-cable-straps",
    description: "Multi-color silicon organizers - 15 pieces",
    descriptionAr: "منظمات سيليكون متعددة الألوان - 15 قطعة",
    price: 38,
    category: "Workspace",
    featured: false,
    image: "🌈",
    images: ["🌈"],
    colors: "Black, White, Matcha Green, Blue, Gray Blue",
    packaging: "Each pack contains (3 Black, 3 White, 3 Green, 3 Ice Blue, 3 Gray Blue)",
    detailedDescription: "Flexible silicon cable straps in beautiful modern colors. Soft-touch material won't damage cables while providing secure hold. Perfect for organizing charging cables, headphone wires, or bundling cords behind desks and entertainment centers. Durable silicon material is heat-resistant and long-lasting.",
    detailedDescriptionAr: "أشرطة كابلات سيليكون مرنة بألوان عصرية جميلة. مادة ناعمة الملمس لن تضر بالكابلات مع توفير ثبات آمن. مثالية لتنظيم كابلات الشحن أو أسلاك سماعات الرأس أو ربط الأسلاك خلف المكاتب ومراكز الترفيه. مادة السيليكون المتينة مقاومة للحرارة وطويلة الأمد.",
    specifications: [
      "15 pieces total",
      "Premium silicon material",
      "Heat-resistant",
      "Soft-touch design",
      "Won't damage cables",
      "Colors: Black, White, Matcha Green, Ice Blue, Gray Blue"
    ]
  },
  {
    id: 5,
    name: "Black Silicon Cable Straps (15 Pack)",
    nameAr: "أشرطة سيليكون سوداء للكابلات (15 قطعة)",
    slug: "black-silicon-cable-straps-15pack",
    description: "Professional black silicon straps - 15 pieces",
    descriptionAr: "أشرطة سيليكون سوداء احترافية - 15 قطعة",
    price: 35,
    category: "Workspace",
    featured: false,
    image: "⬛",
    images: ["⬛"],
    colors: "Black",
    packaging: "Each pack contains (15 Black)",
    detailedDescription: "Premium black silicon cable straps for a professional, minimalist aesthetic. Perfect for high-end installations where cable management needs to be invisible yet effective. Flexible silicon material provides secure hold without scratching or damaging expensive cables. Ideal for professional workstations, studios, or premium home setups.",
    detailedDescriptionAr: "أشرطة كابلات سيليكون سوداء فاخرة لجمالية احترافية وبسيطة. مثالية للتركيبات الراقية حيث تحتاج إدارة الكابلات إلى أن تكون غير مرئية لكنها فعالة. توفر مادة السيليكون المرنة ثباتاً آمناً دون خدش أو إتلاف الكابلات باهظة الثمن. مثالية لمحطات العمل الاحترافية أو الاستوديوهات أو الإعدادات المنزلية المتميزة.",
    specifications: [
      "15 pieces (all black)",
      "Premium silicon material",
      "Heat-resistant",
      "Professional appearance",
      "Won't damage cables",
      "Flexible and durable"
    ]
  },
  {
    id: 6,
    name: "Desk Organizer",
    nameAr: "منظم مكتب",
    slug: "desk-organizer",
    description: "Multi-compartment desk caddy",
    descriptionAr: "منظم مكتب متعدد الأقسام",
    price: 85,
    category: "Workspace",
    featured: true,
    image: "📝",
    images: ["📝"]
  },
  {
    id: 7,
    name: "Smart Plug",
    nameAr: "مقبس ذكي",
    slug: "smart-plug",
    description: "WiFi-enabled smart socket",
    descriptionAr: "مقبس ذكي بخاصية WiFi",
    price: 55,
    category: "Home",
    featured: true,
    image: "🔌",
    images: ["🔌"]
  },
  {
    id: 8,
    name: "USB Hub",
    nameAr: "موزع USB",
    slug: "usb-hub",
    description: "7-port USB 3.0 hub",
    descriptionAr: "موزع USB 3.0 بـ 7 منافذ",
    price: 75,
    category: "Workspace",
    featured: false,
    image: "🔗",
    images: ["🔗"]
  },
  {
    id: 9,
    name: "Product 9",
    nameAr: "منتج 9",
    slug: "product-9",
    description: "Placeholder product 9",
    descriptionAr: "منتج تجريبي 9",
    price: 100,
    category: "Home",
    featured: false,
    image: "🎁",
    images: ["🎁"]
  },
  {
    id: 10,
    name: "Product 10",
    nameAr: "منتج 10",
    slug: "product-10",
    description: "Placeholder product 10",
    descriptionAr: "منتج تجريبي 10",
    price: 90,
    category: "Workspace",
    featured: false,
    image: "🎉",
    images: ["🎉"]
  }
];

const categoryTranslations = {
  "All Products": "جميع المنتجات",
  "Workspace": "مساحة العمل",
  "Phone Accessories": "إكسسوارات الهاتف",
  "Home": "المنزل",
  "Car Accessories": "إكسسوارات السيارة"
};
